### ISSUE TITLE
Props not loading

### ISSUE THREAD

**Issue by HTokko23** [IamLation/lation_mining#8] opened 2024-12-31 15:16 UTC
Lets say I have in config 10 rocks down to spawn sometimes for some players it would only show 3 and not all 10.

**Comment by IamLation** [comment] 2024-12-31 15:57
Tried to reproduce so I set my config to have 10 rocks, loaded in on two clients, and both clients saw all 10. Unable to replicate and also due to failure to follow template thus missing vital info such as screenshots/videos/repro steps/etc, closing.

**Comment by HTokko23** [comment] 2024-12-31 15:58
Its not always tho its random sorry couldnt get a SS of it.

**Closed by IamLation** 2024-12-31 15:57 UTC
Labels: bug

**Comment by IamLation** [comment] 2024-12-31 16:00
> Its not always tho its random sorry couldnt get a SS of it.

Try to research more into the issue and document what may cause it / how to replicate it. If it's a valid issue I want to fix it, but with the little to 0 information provided here there's nothing for me to work off of. So, give it time, gather info, compile it nicely and follow the template, get videos/something and I can get to work on it.
